# Generated by Django 3.2.6 on 2021-08-13 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 21, 53, 8, 637196), verbose_name='Fecha de publicación'),
        ),
    ]
