# Generated by Django 3.2.6 on 2021-08-16 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='curso_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 16, 51, 32, 96557), verbose_name='Fecha de publicación'),
        ),
    ]
