# Generated by Django 3.2.6 on 2021-08-17 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210816_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 16, 3, 32, 222557), verbose_name='Fecha de publicación'),
        ),
    ]
