# Generated by Django 3.2.6 on 2021-08-17 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 16, 6, 10, 881418), verbose_name='Fecha de publicación'),
        ),
    ]
