# Generated by Django 3.2.6 on 2021-08-18 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 18, 30, 21, 11096), verbose_name='Fecha de publicación'),
        ),
    ]
