# Generated by Django 3.2.6 on 2021-08-23 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210823_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 17, 16, 32, 707009), verbose_name='Fecha de publicación'),
        ),
    ]
