# Generated by Django 3.2.6 on 2021-08-26 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 18, 57, 13, 176618), verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(default=1, upload_to='main', verbose_name='images'),
            preserve_default=False,
        ),
    ]
