# Generated by Django 3.2.6 on 2021-08-27 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210826_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 22, 3, 15, 330883), verbose_name='Fecha de publicación'),
        ),
    ]
