# Generated by Django 3.2.6 on 2021-08-27 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_curso_curso_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 15, 46, 45, 73564), verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='images'),
        ),
    ]
