# Generated by Django 3.2.6 on 2021-08-27 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210827_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 16, 11, 59, 382216), verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
