# Generated by Django 3.2.6 on 2021-08-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_alter_inscripcion_costo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='apellidos',
            field=models.CharField(default=15, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='edad',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nombres',
            field=models.CharField(default=15, max_length=100),
            preserve_default=False,
        ),
    ]
